import type { Product } from "./types"

export const products: Product[] = [
  {
    id: "1",
    name: "Camisa Palmeiras I 2024 - Puma",
    price: 249.99,
    image: "/placeholder.svg?height=300&width=300&text=Camisa+Palmeiras",
    category: "Camisas",
    description: "Camisa oficial do Palmeiras temporada 2024, modelo I com tecnologia Puma",
  },
  {
    id: "2",
    name: "Camisa Palmeiras II 2024 - Puma",
    price: 249.99,
    image: "/placeholder.svg?height=300&width=300&text=Camisa+II+Palmeiras",
    category: "Camisas",
    description: "Camisa oficial do Palmeiras temporada 2024, modelo II branca",
  },
  {
    id: "3",
    name: "Boné Palmeiras New Era",
    price: 89.99,
    image: "/placeholder.svg?height=300&width=300&text=Boné+Palmeiras",
    category: "Bonés e Chapéus",
    description: "Boné oficial New Era do Palmeiras com bordado do escudo",
  },
  {
    id: "4",
    name: "Agasalho Palmeiras Puma",
    price: 199.99,
    image: "/placeholder.svg?height=300&width=300&text=Agasalho+Palmeiras",
    category: "Agasalhos",
    description: "Agasalho oficial Puma do Palmeiras com zíper completo",
  },
  {
    id: "5",
    name: "Chaveiro Palmeiras Escudo",
    price: 19.99,
    image: "/placeholder.svg?height=300&width=300&text=Chaveiro+Palmeiras",
    category: "Acessórios",
    description: "Chaveiro oficial do Palmeiras com escudo em metal",
  },
  {
    id: "6",
    name: "Caneca Palmeiras 400ml",
    price: 39.99,
    image: "/placeholder.svg?height=300&width=300&text=Caneca+Palmeiras",
    category: "Casa e Decoração",
    description: "Caneca oficial do Palmeiras em porcelana, 400ml",
  },
  {
    id: "7",
    name: "Shorts Palmeiras Puma",
    price: 89.99,
    image: "/placeholder.svg?height=300&width=300&text=Shorts+Palmeiras",
    category: "Shorts",
    description: "Shorts oficial do Palmeiras para treino e lazer",
  },
  {
    id: "8",
    name: "Mochila Palmeiras Escolar",
    price: 129.99,
    image: "/placeholder.svg?height=300&width=300&text=Mochila+Palmeiras",
    category: "Acessórios",
    description: "Mochila oficial do Palmeiras para escola e viagens",
  },
  {
    id: "9",
    name: "Cachecol Palmeiras Torcida",
    price: 49.99,
    image: "/placeholder.svg?height=300&width=300&text=Cachecol+Palmeiras",
    category: "Acessórios",
    description: "Cachecol oficial da torcida do Palmeiras",
  },
  {
    id: "10",
    name: "Tênis Palmeiras Puma",
    price: 299.99,
    image: "/placeholder.svg?height=300&width=300&text=Tênis+Palmeiras",
    category: "Calçados",
    description: "Tênis oficial Puma do Palmeiras edição especial",
  },
  {
    id: "11",
    name: "Bandeira Palmeiras 1,5x1m",
    price: 59.99,
    image: "/placeholder.svg?height=300&width=300&text=Bandeira+Palmeiras",
    category: "Casa e Decoração",
    description: "Bandeira oficial do Palmeiras para decoração",
  },
  {
    id: "12",
    name: "Carteira Palmeiras Couro",
    price: 79.99,
    image: "/placeholder.svg?height=300&width=300&text=Carteira+Palmeiras",
    category: "Acessórios",
    description: "Carteira em couro sintético com escudo do Palmeiras",
  },
]

export const categories = [...new Set(products.map((p) => p.category))]
